In [1]:
import pandas as pd

## Downloading the Brazilian E-Commerce Public Dataset by Olist

In [2]:
import kagglehub
path = kagglehub.dataset_download("olistbr/brazilian-ecommerce",
                                 output_dir=r"C:\Users\DELL\Desktop\Pandas_in_14_days\Work\Data")
print(path)

C:\Users\DELL\Desktop\Pandas_in_14_days\Work\Data

### Task 1 - Importing olist_orders_dataset with read_csv; use head, tail, shape, info, describe, dtypes

In [3]:
df = pd.read_csv("Data/olist_orders_dataset.csv")

In [4]:
df.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [5]:
df.tail()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
99436,9c5dedf39a927c1b2549525ed64a053c,39bd1228ee8140590ac3aca26f2dfe00,delivered,2017-03-09 09:54:05,2017-03-09 09:54:05,2017-03-10 11:18:03,2017-03-17 15:08:01,2017-03-28 00:00:00
99437,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00
99438,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00
99439,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00
99440,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00

In [6]:
df.shape

(99441, 8)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  str
 1   customer_id                    99441 non-null  str
 2   order_status                   99441 non-null  str
 3   order_purchase_timestamp       99441 non-null  str
 4   order_approved_at              99281 non-null  str
 5   order_delivered_carrier_date   97658 non-null  str
 6   order_delivered_customer_date  96476 non-null  str
 7   order_estimated_delivery_date  99441 non-null  str
dtypes: str(8)
memory usage: 21.9 MB

In [8]:
df.describe()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
count,99441,99441,99441,99441,99281,97658,96476,99441
unique,99441,99441,8,98875,90733,81018,95664,459
top,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2018-03-31 15:08:21,2018-02-27 04:31:10,2018-05-09 15:48:00,2018-05-14 20:02:44,2017-12-20 00:00:00
freq,1,1,96478,3,9,47,3,522

#### count: the number of non-null values.
#### unique: the number of distinct values (3 cities).
#### top: the most frequent value
#### freq: how often top appears

In [9]:
df.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

### Task 2 - Compare a Series and a DataFrame; pull out one column of each kind

In [10]:
s = df["order_status"]
print(type(s))
s.shape

<class 'pandas.Series'>

(99441,)

In [11]:
s.dtype

In [12]:
s.ndim

1

In [13]:
s.name
# s.columns -- not available for series, use series.name instead

'order_status'

In [14]:
s.index

RangeIndex(start=0, stop=99441, step=1)

In [15]:
d = df[["order_status"]]
print(type(d))

d.shape

<class 'pandas.DataFrame'>

(99441, 1)

In [16]:
d.dtypes

order_status    str
dtype: object

In [17]:
d.ndim

2

In [18]:
# d.name -- not available for dataframe, since it does not have a single name. Use df.columns instead
d.columns

Index(['order_status'], dtype='str')

In [19]:
d.index

RangeIndex(start=0, stop=99441, step=1)

### Task 3 - Save a subset to CSV and to Parquet with to_csv and to_parquet

In [20]:
df_to_csv = df.sample(20)
df_to_csv.to_csv("orders_sample_to_csv.csv", index=False)

In [21]:
# For saving a file as parquet we require the pyarrow or the fastparquet package.
# The default behaviour is to try pyarrow first and then fallback to fastparquet it pyarrow is not available.

df_to_parquet = df.sample(30)
df_to_parquet.to_parquet("orders_sample_to_parquet.parquet")

### Exercise - Load all 9 Olist tables into a dictionary of DataFrames. Print the shape and null count of each. Write down which columns look like keys.

Path(...) turns the folder string into a path object, which has useful methods like glob. It also handles Windows backslashes and joining paths cleanly.

glob("*.csv") searches that folder for files whose names match a pattern. * means “anything”, so *.csv matches every file ending in .csv. It returns the matching file paths one by one. Other patterns work too:

glob("olist_*"): files starting with olist_
glob("*order*.csv"): CSV files with “order” in the name
rglob("*.csv"): also searches inside sub-folders

f.stem is the file name without the folder and without the extension. For C:\...\Data\olist_orders_dataset.csv:

f.name gives olist_orders_dataset.csv
f.stem gives olist_orders_dataset
f.suffix gives .csv

The dictionary comprehension {f.stem: pd.read_csv(f) for f in ...} loops over every CSV file, reads it into a DataFrame, and stores it under its stem. The result is a dictionary, with file names as keys and DataFrames as values:

In [24]:
## Load all the 9 tables together

from pathlib import Path

data_dir = Path(r"C:\Users\DELL\Desktop\Pandas_in_14_days\Work\Data")
tables = {f.stem: pd.read_csv(f) for f in data_dir.glob("*.csv")}

for name, df in tables.items():
    print(name, df.shape)

olist_customers_dataset (99441, 5)
olist_geolocation_dataset (1000163, 5)
olist_orders_dataset (99441, 8)
olist_order_items_dataset (112650, 7)
olist_order_payments_dataset (103886, 5)
olist_order_reviews_dataset (99224, 7)
olist_products_dataset (32951, 9)
olist_sellers_dataset (3095, 4)
product_category_name_translation (71, 2)

In [27]:
## Print count of null values in each column of a dataframe

for key in tables.keys():
    count_of_nulls = tables[key].isna().sum()
    print(count_of_nulls)

customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64
product_category_name            0
product_category_name_english    0
dtype: int64

In [29]:
## Print count of null values in each column of a dataframe

for key, value in tables.items():
    print(key, value.shape)
    print(value.isna().sum())

olist_customers_dataset (99441, 5)
customer_id                 0
customer_unique_id          0
customer_zip_code_prefix    0
customer_city               0
customer_state              0
dtype: int64
olist_geolocation_dataset (1000163, 5)
geolocation_zip_code_prefix    0
geolocation_lat                0
geolocation_lng                0
geolocation_city               0
geolocation_state              0
dtype: int64
olist_orders_dataset (99441, 8)
order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64
olist_order_items_dataset (112650, 7)
order_id               0
order_item_id          0
product_id             0
seller_id              0
shipping_limit_date    0
price                  0
freight_value          0
dtype: int64
olist_order_payments_dataset (103886, 5)
order_id                0
payment_sequential      0
payment_type            0
payment_installments    0
payment_value           0
dtype: int64
olist_order_reviews_dataset (99224, 7)
review_id                      0
order_id                       0
review_score                   0
review_comment_title       87656
review_comment_message     58247
review_creation_date           0
review_answer_timestamp        0
dtype: int64
olist_products_dataset (32951, 9)
product_id                      0
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64
olist_sellers_dataset (3095, 4)
seller_id                 0
seller_zip_code_prefix    0
seller_city               0
seller_state              0
dtype: int64
product_category_name_translation (71, 2)
product_category_name            0
product_category_name_english    0
dtype: int64

In [30]:
## Print count of null values in total in a dataframe (adding up from all the columns)

for key, value in tables.items():
    print(key, value.shape)
    print(value.isna().sum().sum())

olist_customers_dataset (99441, 5)
0
olist_geolocation_dataset (1000163, 5)
0
olist_orders_dataset (99441, 8)
4908
olist_order_items_dataset (112650, 7)
0
olist_order_payments_dataset (103886, 5)
0
olist_order_reviews_dataset (99224, 7)
145903
olist_products_dataset (32951, 9)
2448
olist_sellers_dataset (3095, 4)
0
product_category_name_translation (71, 2)
0