In [5]:
import pandas as pd
from pathlib import Path

## Import all the 9 tables together

In [6]:
data_dir = Path(r"C:\Users\DELL\Desktop\Pandas_in_14_days\Work\Data")
tables = {f.stem : pd.read_csv(f) for f in data_dir.glob("*.csv")}

for name, df in tables.items():
    print(name, df.shape)

olist_customers_dataset (99441, 5)
olist_geolocation_dataset (1000163, 5)
olist_orders_dataset (99441, 8)
olist_order_items_dataset (112650, 7)
olist_order_payments_dataset (103886, 5)
olist_order_reviews_dataset (99224, 7)
olist_products_dataset (32951, 9)
olist_sellers_dataset (3095, 4)
product_category_name_translation (71, 2)

## Creating copies of all the values of "tables" dictionary, so that the original dataset stays intact

In [7]:
customers   = tables["olist_customers_dataset"].copy()
geolocation = tables["olist_geolocation_dataset"].copy()
items       = tables["olist_order_items_dataset"].copy()
payments    = tables["olist_order_payments_dataset"].copy()
reviews     = tables["olist_order_reviews_dataset"].copy()
orders      = tables["olist_orders_dataset"].copy()
products    = tables["olist_products_dataset"].copy()
sellers     = tables["olist_sellers_dataset"].copy()
category_translation = tables["product_category_name_translation"].copy()

## Task 1 - Use loc and iloc for rows and columns

### 1.1 Using iloc, show the first 5 rows of orders with only the 1st, 4th and 6th columns.

In [10]:
orders.iloc[:5,[0,3,5]]

,order_id,order_purchase_timestamp,order_delivered_carrier_date
0,e481f51cbdc54678b7cc49136f2d6af7,2017-10-02 10:56:33,2017-10-04 19:55:00
1,53cdb2fc8bc7dce0b6741e2150273451,2018-07-24 20:41:37,2018-07-26 14:31:00
2,47770eb9100c2d0c44946d9cf07ec65d,2018-08-08 08:38:49,2018-08-08 13:50:00
3,949d5b44dbf5de918fe9c16f97b45f8a,2017-11-18 19:28:06,2017-11-22 13:39:59
4,ad21c59c0840e6cb83a9ceb5573f8159,2018-02-13 21:18:39,2018-02-14 19:46:34

### 1.2 Using loc, show the rows labelled 100 to 104 of orders, keeping only order_id and order_status.

In [11]:
orders.loc[100:104,['order_id','order_status']]

                             order_id order_status
100  e3447938231fb6ba2fee0231b51eca59    delivered
101  e346cd9299371b18c0b28e8e29a5e376    delivered
102  a5474c0071dd5d1074e12d417078bbd0    delivered
103  0760a852e4e9d89eb77bf631eaaf1c84     invoiced
104  bb7c5cf4dff9994daeab7c8ee9d287aa    delivered

In [12]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [13]:
orders.iloc[100:104, [0,2]]

                             order_id order_status
100  e3447938231fb6ba2fee0231b51eca59    delivered
101  e346cd9299371b18c0b28e8e29a5e376    delivered
102  a5474c0071dd5d1074e12d417078bbd0    delivered
103  0760a852e4e9d89eb77bf631eaaf1c84     invoiced

#### Here loc and iloc give a different number of rows, because while using the loc function, the end in loc[start:end] is inclusive, where as while using iloc, it is exclusive. This is because in dataframes the index or labels can be a string as well; it is not necessary that it will always be a number.

### 1.3 Find the value in the 10th row of the price column of items in three ways: with iloc, with loc, and with items['price'].iloc[9].

In [14]:
items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [20]:
print(items.iloc[9,5])

53.99

In [18]:
print(items.loc[9,'price'])

53.99

In [19]:
print(items['price'].iloc[9])

53.99

### 1.4 From customers, select rows 0 to 9 and every column from customer_city to customer_state, using one label slice on the columns.

In [21]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [22]:
customers.iloc[0:10,-2:]

           customer_city customer_state
0                 franca             SP
1  sao bernardo do campo             SP
2              sao paulo             SP
3        mogi das cruzes             SP
4               campinas             SP
5         jaragua do sul             SC
6              sao paulo             SP
7                timoteo             MG
8               curitiba             PR
9         belo horizonte             MG

In [23]:
customers.loc[0:9, 'customer_city' : 'customer_state']

           customer_city customer_state
0                 franca             SP
1  sao bernardo do campo             SP
2              sao paulo             SP
3        mogi das cruzes             SP
4               campinas             SP
5         jaragua do sul             SC
6              sao paulo             SP
7                timoteo             MG
8               curitiba             PR
9         belo horizonte             MG

### 1.5 Show the last 3 rows of payments in two ways: with tail(3), and with iloc and a negative position.

In [24]:
payments.tail(3)

,order_id,payment_sequential,payment_type,payment_installments,payment_value
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

In [26]:
payments.iloc[-3:]

,order_id,payment_sequential,payment_type,payment_installments,payment_value
103883,32609bbb3dd69b3c066a6860554a77bf,1,credit_card,1,47.77
103884,b8b61059626efa996a60be9bb9320e10,1,credit_card,5,369.54
103885,28bbae6599b09d39ca406b747b6632b1,1,boleto,1,191.58

## Task 2 - Filter with boolean masks using &, |, ~, isin, between

### 2.1 How many orders have order_status equal to 'delivered'?

In [33]:
(orders.order_status == 'delivered').sum()

np.int64(96478)

### 2.2 Show the orders whose status is either 'canceled' or 'unavailable', first using | and then using isin. Confirm both give the same number of rows.

In [38]:
#orders.head(3)
orders[(orders.order_status == 'canceled') | (orders.order_status == 'unavailable')].shape

(1234, 8)

In [42]:
orders[orders.order_status.isin(['canceled','unavailable'])].shape

(1234, 8)

### 2.3 Find the items where price is above 1000 and freight_value is below 50. How many are there?

In [43]:
items.head(3)

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.0,17.87

In [47]:
items[(items.price > 1000) & (items.freight_value < 50)].shape

(496, 7)

### 2.4 Find the items with price between 100 and 200 (inclusive) using between(). Then find the items outside that range using ~. Check that the two counts add up to the total number of items.

In [61]:
condition = items.price.between(100, 200, inclusive='both')

a = items[condition].shape
b = items[~condition].shape
print(a)
print(b)

(27111, 7)
(85539, 7)

In [63]:
c = items.shape
print(c)

(112650, 7)

In [64]:
a[0] + b[0] == c[0]

True

### 2.5 Find the reviews with a review_score of 1 that also have a written comment (review_comment_message is not empty)

In [65]:
reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [68]:
reviews.info()

<class 'pandas.DataFrame'>
RangeIndex: 99224 entries, 0 to 99223
Data columns (total 7 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   review_id                99224 non-null  str
 1   order_id                 99224 non-null  str
 2   review_score             99224 non-null  int64
 3   review_comment_title     11568 non-null  str
 4   review_comment_message   40977 non-null  str
 5   review_creation_date     99224 non-null  str
 6   review_answer_timestamp  99224 non-null  str
dtypes: int64(1), str(6)
memory usage: 17.8 MB

In [69]:
reviews[(reviews.review_score == 1) & (reviews.review_comment_message.notnull())].shape[0]

8745

## Task 3 - Filter with query() and compare readability

### Basically using query we can write the expressions to filter data in normal python syntax inside the quotes. That is the difference between using boolean masks and query()

### 3.1 Redo 2.3 (price above 1000 and freight_value below 50) with query(). Does the row count match your earlier answer?

In [74]:
items.query("price > 1000 and freight_value < 50").shape[0]

496

### 3.2 Set a Python variable min_price = 500. Use query() to find the items priced above it, without typing 500 inside the query.

In [76]:
min_price = 500
items.query("price > @min_price")

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10 12:30:45,810.0,70.75
16,0009c9a17f916a706d71784483a5d643,1,3f27ac8e699df3d300ec4a5d8c5cf0b2,fcb5ace8bcc92f75707dc0f01a27d269,2018-05-02 09:31:53,639.0,11.34
39,0017afd5076e074a48f1f1a4c7bac9c5,1,fe59a1e006df3ac42bf0ceb876d70969,25c5c91f63607446a97b143d2d535d31,2017-04-24 22:25:19,809.1,44.29
158,006127b8b9a1681a982313ed7129c3c0,1,f819f0c84a64f02d3a5606ca95edd272,7d13fca15225358621be4086e1eb0964,2018-03-15 02:30:23,540.0,16.22
265,00ab9fa91aafa3d881164b0da48999aa,1,224037b21bfa8621e39c265513ee6594,ceaec5548eefc6e23e6607c5435102e7,2018-06-04 09:50:04,579.0,65.34
...,...,...,...,...,...,...,...
112449,ff85c3e4329457e83cb474799a257ccc,1,144266e1585320d057797a369596bb8b,850f4f8af5ea87287ac68de36e29107f,2018-01-24 16:57:45,899.0,17.50
112553,ffc2638415f3ce34e88641eef792c1fc,1,bc2d6310e5cbd60facb2f9c8d9471597,dc317f341ab0e22f39acbd9dbf9b4a1f,2017-06-12 13:41:58,629.0,67.08
112557,ffc49b9c9d666410e9ecdb0a3efadb9c,1,f96ff9b997681965689f78bef092fdd9,2a5b78b41cd05baeac8df54c6606b92c,2018-06-05 19:56:23,765.0,27.06
112571,ffd5e80bfdaf69504efd7562a3d522dd,1,bd67e67dcfcc53e712a29c215ec26de5,3d39fbf22a665714baf62fae36029e23,2017-08-28 09:46:08,584.9,16.65
112632,fff7c4452f050315db1b3f24d9df5fcd,1,dd469c03ad67e201bc2179ef077dcd48,7e93a43ef30c4f03f38b393420bc753a,2017-06-07 17:05:23,736.0,20.91

### 3.3 Use query() to find the customers whose customer_state is SP, RJ or MG.

In [77]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [79]:
customers.query("customer_state in ['SP', 'RJ', 'MG']")

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99434,f5a0b560f9e9427792a88bec97710212,b3e53d18a997f27a3ffd16da497eaf58,7790,cajamar,SP
99435,7fe2e80252a9ea476f950ae8f85b0f8f,4b5820135d360a45552b5163835b1d89,35500,divinopolis,MG
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

##  Task 4 - Add and rename columns; use sort_values on one and several columns

### 4.1 Add a column total_value to items equal to price + freight_value. Show the first 5 rows and check one row by hand.

In [80]:
items['total_value'] = items['price'] + items['freight_value']
items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,72.19
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,259.83
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,216.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,25.78
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,218.04

### 4.2 Add a column is_expensive to items that is True when price is above 500.

In [83]:
items['isexpensive'] = (items.price > 500)
items[items.price > 500]

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,total_value,isexpensive
7,000576fe39319847cbb9d288c5617fa6,1,557d850972a7d6f792fd18ae1400d9b6,5996cddab893a4652a15592fb58ab8db,2018-07-10 12:30:45,810.0,70.75,880.75,True
16,0009c9a17f916a706d71784483a5d643,1,3f27ac8e699df3d300ec4a5d8c5cf0b2,fcb5ace8bcc92f75707dc0f01a27d269,2018-05-02 09:31:53,639.0,11.34,650.34,True
39,0017afd5076e074a48f1f1a4c7bac9c5,1,fe59a1e006df3ac42bf0ceb876d70969,25c5c91f63607446a97b143d2d535d31,2017-04-24 22:25:19,809.1,44.29,853.39,True
158,006127b8b9a1681a982313ed7129c3c0,1,f819f0c84a64f02d3a5606ca95edd272,7d13fca15225358621be4086e1eb0964,2018-03-15 02:30:23,540.0,16.22,556.22,True
265,00ab9fa91aafa3d881164b0da48999aa,1,224037b21bfa8621e39c265513ee6594,ceaec5548eefc6e23e6607c5435102e7,2018-06-04 09:50:04,579.0,65.34,644.34,True
...,...,...,...,...,...,...,...,...,...
112449,ff85c3e4329457e83cb474799a257ccc,1,144266e1585320d057797a369596bb8b,850f4f8af5ea87287ac68de36e29107f,2018-01-24 16:57:45,899.0,17.50,916.50,True
112553,ffc2638415f3ce34e88641eef792c1fc,1,bc2d6310e5cbd60facb2f9c8d9471597,dc317f341ab0e22f39acbd9dbf9b4a1f,2017-06-12 13:41:58,629.0,67.08,696.08,True
112557,ffc49b9c9d666410e9ecdb0a3efadb9c,1,f96ff9b997681965689f78bef092fdd9,2a5b78b41cd05baeac8df54c6606b92c,2018-06-05 19:56:23,765.0,27.06,792.06,True
112571,ffd5e80bfdaf69504efd7562a3d522dd,1,bd67e67dcfcc53e712a29c215ec26de5,3d39fbf22a665714baf62fae36029e23,2017-08-28 09:46:08,584.9,16.65,601.55,True
112632,fff7c4452f050315db1b3f24d9df5fcd,1,dd469c03ad67e201bc2179ef077dcd48,7e93a43ef30c4f03f38b393420bc753a,2017-06-07 17:05:23,736.0,20.91,756.91,True

### 4.3 Make a new DataFrame from customers in which customer_zip_code_prefix is renamed to zip_prefix. Check that the original customers still has the old name.

In [87]:
customers.rename(columns={'customer_zip_code_prefix' : 'zip_prefix'})
#customers_col_changed.head()

,customer_id,customer_unique_id,zip_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP
...,...,...,...,...,...
99436,17ddf5dd5d51696bb3d7c6291687be6f,1a29b476fee25c95fbafc67c5ac95cf8,3937,sao paulo,SP
99437,e7b71a9017aa05c9a7fd292d714858e8,d52a67c98be1cf6a5c84435bd38d095d,6764,taboao da serra,SP
99438,5e28dfe12db7fb50a4b2f691faecea5e,e9f50caf99f032f0bf3c55141f019d99,60115,fortaleza,CE
99439,56b18e2166679b8a959d72dd06da27f9,73c2643a0a458b49f58cea58833b192e,92120,canoas,RS
99440,274fa6071e5e17fe303b9748641082c8,84732c5050c01db9b23e19ba39899398,6703,cotia,SP

In [88]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

### 4.4 Show the 10 most expensive items (columns product_id and price only). Then sort by price descending and freight_value ascending. What changes for rows with the same price?

In [99]:
#items.columns.get_loc('product_id')
#items.columns.get_loc('price')
items.sort_values(by='price', ascending=False).iloc[0:10, [2,5]]

                              product_id    price
3556    489ae2aa008f021502940f251d4cce7f  6735.00
112233  69c590f7ffc7bf8db97190b6cb6ed62e  6729.00
107841  1bdf5e6731585cf01aa8169c7028d6ad  6499.00
74336   a6492cc69376c469ab6f61d8f44de961  4799.00
11249   c3ed642d592594bb648ff4a04cee2747  4690.00
62086   259037a6a41845e455183f89c5035f18  4590.00
29193   a1beef8f3992dbd4cd8726796aa69c53  4399.87
45843   6cdf8fc1d741c76586d8b6b15e9eef30  4099.99
78310   dd113cb02b2af9c8e5787e8f1f0722f6  4059.00
59137   6902c1962dd19d540807d0ab8fade5c6  3999.90

In [100]:
items.sort_values(by=['price','freight_value'], ascending=[False,True]).iloc[:10,[2,5]]

                              product_id    price
3556    489ae2aa008f021502940f251d4cce7f  6735.00
112233  69c590f7ffc7bf8db97190b6cb6ed62e  6729.00
107841  1bdf5e6731585cf01aa8169c7028d6ad  6499.00
74336   a6492cc69376c469ab6f61d8f44de961  4799.00
11249   c3ed642d592594bb648ff4a04cee2747  4690.00
62086   259037a6a41845e455183f89c5035f18  4590.00
29193   a1beef8f3992dbd4cd8726796aa69c53  4399.87
45843   6cdf8fc1d741c76586d8b6b15e9eef30  4099.99
78310   dd113cb02b2af9c8e5787e8f1f0722f6  4059.00
59137   6902c1962dd19d540807d0ab8fade5c6  3999.90

### 4.5 Sort orders by order_purchase_timestamp from oldest to newest and show the first 5 rows. Why does sorting this text column give the right order here, and when would it not?

#### The format is year-month-day hour:minute:second, so alphabetical order matches time order. A format like 25/12/2018 would sort by day first and give the wrong order.

In [101]:
orders.sort_values(by='order_purchase_timestamp').head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
4541,2e7a8482f6fb09756ca50c10d7bfc047,08c5351a6aca1c1589a38f244edeee9d,shipped,2016-09-04 21:15:19,2016-10-07 13:18:03,2016-10-18 13:14:51,NaN,2016-10-20 00:00:00
4396,e5fa5a7210941f7d56d0208e4e071d35,683c54fc24d40ee9f8a6fc179fd9856c,canceled,2016-09-05 00:15:34,2016-10-07 13:17:15,NaN,NaN,2016-10-28 00:00:00
10071,809a282bbd5dbcabb6f2f724fca862ec,622e13439d6b5a0b486c435618b2679e,canceled,2016-09-13 15:24:19,2016-10-07 13:16:46,NaN,NaN,2016-09-30 00:00:00
30710,bfbd0f9bdef84302105ad712db648a6c,86dc2ffce2dfff336de2f386a786e574,delivered,2016-09-15 12:16:38,2016-09-15 12:16:38,2016-11-07 17:11:53,2016-11-09 07:47:38,2016-10-04 00:00:00
83078,71303d7e93b399f5bcd537d124c0bcfa,b106b360fe2ef8849fbbd056f777b4d5,canceled,2016-10-02 22:07:52,2016-10-06 15:50:56,NaN,NaN,2016-10-25 00:00:00