In [1]:
import pandas as pd
from pathlib import Path

print("Done")

Done

In [2]:
data_dir = Path(r"C:\Users\DELL\Desktop\Pandas_in_14_days\Work\Data")
tables = {f.stem : pd.read_csv(f) for f in data_dir.glob("*.csv")}

for name, df in tables.items():
    print(name, df.shape)

olist_customers_dataset (99441, 5)
olist_geolocation_dataset (1000163, 5)
olist_orders_dataset (99441, 8)
olist_order_items_dataset (112650, 7)
olist_order_payments_dataset (103886, 5)
olist_order_reviews_dataset (99224, 7)
olist_products_dataset (32951, 9)
olist_sellers_dataset (3095, 4)
product_category_name_translation (71, 2)

In [3]:
customers   = tables["olist_customers_dataset"].copy()
geolocation = tables["olist_geolocation_dataset"].copy()
items       = tables["olist_order_items_dataset"].copy()
payments    = tables["olist_order_payments_dataset"].copy()
reviews     = tables["olist_order_reviews_dataset"].copy()
orders      = tables["olist_orders_dataset"].copy()
products    = tables["olist_products_dataset"].copy()
sellers     = tables["olist_sellers_dataset"].copy()
category_translation = tables["product_category_name_translation"].copy()

## Task 1 - Count nulls per column with isna().sum() and as a percentage

### 1.1 Count the nulls in every column of orders, sorted from most to least. Which columns have nulls? You should see roughly 2,965 for order_delivered_customer_date.

In [4]:
orders.isna().sum().sort_values(ascending=False)

order_delivered_customer_date    2965
order_delivered_carrier_date     1783
order_approved_at                 160
order_id                            0
order_purchase_timestamp            0
order_status                        0
customer_id                         0
order_estimated_delivery_date       0
dtype: int64

### 1.2 For products, show the percentage of missing values per column, rounded to 2 decimals, keeping only columns with at least one null.

In [5]:
series = (products.isna().mean()*100).round(2)
series[series > 0]

product_category_name         1.85
product_name_lenght           1.85
product_description_lenght    1.85
product_photos_qty            1.85
product_weight_g              0.01
product_length_cm             0.01
product_height_cm             0.01
product_width_cm              0.01
dtype: float64

In [6]:
series

product_id                    0.00
product_category_name         1.85
product_name_lenght           1.85
product_description_lenght    1.85
product_photos_qty            1.85
product_weight_g              0.01
product_length_cm             0.01
product_height_cm             0.01
product_width_cm              0.01
dtype: float64

### 1.3 In orders, how many rows are 'delivered' but have no order_delivered_customer_date? How many have a delivery date but a status other than 'delivered'? What does this tell you about trusting the status column?

In [7]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [8]:
orders[(orders.order_status == 'delivered') & (pd.isnull(orders.order_delivered_customer_date))].shape[0]

8

In [9]:
orders[(orders.order_status == 'delivered') & (pd.isnull(orders.order_delivered_customer_date))]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaN,2017-12-18 00:00:00
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaN,2018-07-16 00:00:00
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaN,2018-07-30 00:00:00
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaN,2018-07-24 00:00:00
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaN,NaN,2017-06-23 00:00:00
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaN,2018-06-26 00:00:00
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaN,2018-07-19 00:00:00

In [10]:
orders[(pd.notnull(orders.order_delivered_customer_date)) & (orders.order_status != 'delivered')].shape[0]

6

In [11]:
orders[(pd.notnull(orders.order_delivered_customer_date)) & (orders.order_status != 'delivered')]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
2921,1950d777989f6a877539f53795b4c3c3,1bccb206de9f0f25adc6871a1bcf77b2,canceled,2018-02-19 19:48:52,2018-02-19 20:56:05,2018-02-20 19:57:13,2018-03-21 22:03:51,2018-03-09 00:00:00
8791,dabf2b0e35b423f94618bf965fcb7514,5cdec0bb8cbdf53ffc8fdc212cd247c6,canceled,2016-10-09 00:56:52,2016-10-09 13:36:58,2016-10-13 13:36:59,2016-10-16 14:36:59,2016-11-30 00:00:00
58266,770d331c84e5b214bd9dc70a10b829d0,6c57e6119369185e575b36712766b0ef,canceled,2016-10-07 14:52:30,2016-10-07 15:07:10,2016-10-11 15:07:11,2016-10-14 15:07:11,2016-11-29 00:00:00
59332,8beb59392e21af5eb9547ae1a9938d06,bf609b5741f71697f65ce3852c5d2623,canceled,2016-10-08 20:17:50,2016-10-09 14:34:30,2016-10-14 22:45:26,2016-10-19 18:47:43,2016-11-30 00:00:00
92636,65d1e226dfaeb8cdc42f665422522d14,70fc57eeae292675927697fe03ad3ff5,canceled,2016-10-03 21:01:41,2016-10-04 10:18:57,2016-10-25 12:14:28,2016-11-08 10:58:34,2016-11-25 00:00:00
94399,2c45c33d2f9cb8ff8b1c86cc28c11c30,de4caa97afa80c8eeac2ff4c8da5b72e,canceled,2016-10-09 15:39:56,2016-10-10 10:40:49,2016-10-14 10:40:50,2016-11-09 14:53:50,2016-12-08 00:00:00

## Task 2 - Choose between dropna, fillna, and leaving nulls alone, and write down why for each column


### 2.1 For each of these columns, decide whether to drop the rows, fill the nulls, or leave them, and write one sentence on why: orders.order_delivered_customer_date, products.product_category_name, products.product_weight_g, reviews.review_comment_message.

### My Answer
Nulls in orders.order_delivered_customer_date should be left as it is, since it is timestamp column.

Nulls in products.product_category_nme can be filled with "Unknown" 

Nulls in products.product_weight_g can be filled with the mean weight of the column

Nulls in reviews.review_comment_message can be left as it is.

### Right answer
1. order_delivered_customer_date: leave it. The decision is right, but “it is a timestamp column” isn’t the reason. The type doesn’t matter. The reason is what the null means: the order hasn’t been delivered, was canceled, or is still in transit. A null here is real information, and filling it would invent a delivery that never happened. Also don’t drop these rows from orders, because that would remove canceled and undelivered orders from your order counts. Drop them only inside a calculation that needs a delivery date, such as delivery time.

2. product_category_name: fill with “unknown”. This is right. You keep the product rows and make the missing category an explicit group, so it shows up in group counts instead of disappearing. Use lowercase 'unknown' so it matches the style of the other category names.

3. product_weight_g: use the median, not the mean. Filling is the right idea, since only a couple of products are missing a weight and dropping them would waste their other data. The median is the safer fill, because a few very heavy products pull the mean up, while the median stays near a typical product. With only about 2 missing values the practical effect is tiny, but the median is the better habit. A step beyond that is the median weight within the same product category, since a book and a sofa don’t weigh the same.

4. review_comment_message: leave it. Correct. A null means the customer left no comment. That is not a data error, and many reviews have only a score. Filling with something like “no comment” would add fake text that shows up in word counts and searches. When you analyze comments, use na=False in string filters (such as .str.contains('x', na=False)) so the nulls don’t cause errors.

A pattern for these decisions: ask what the null means. If it means “hasn’t happened” or “was not given”, leave it. If it means “wasn’t recorded” for something every row should have, fill it with a placeholder or a typical value. If the row is useless without that value, drop it.

In [12]:
products.product_category_name.isna().sum()

np.int64(610)

In [13]:
#products.head()
values = {"product_category_name" : "unknown"}
products_clean = products.fillna(value = values, axis = 0)

In [14]:
products_clean[products_clean.product_category_name == "unknown"].shape

(610, 9)

In [15]:
products_clean.product_category_name.isna().sum()

np.int64(0)

In [16]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [17]:
products.product_weight_g.isna().sum()

np.int64(2)

In [18]:
values = {"product_weight_g" : products.product_weight_g.median()}
products_clean_2 = products.fillna(values)

In [19]:
#produces a series this way
products_clean_2.product_weight_g.isna().sum()

np.int64(0)

In [20]:
products.product_weight_g.fillna(products.product_weight_g.median())

0          225.0
1         1000.0
2          154.0
3          371.0
4          625.0
          ...
32946    12300.0
32947     1700.0
32948     1400.0
32949      700.0
32950     2083.0
Name: product_weight_g, Length: 32951, dtype: float64

### 2.2 In a copy of products, fill the missing product_category_name values with 'unknown'. Confirm no nulls remain in that column and the original products still has them.

In [22]:
#products.head()
products[products.product_category_name.isna()]

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
105,a41e356c76fab66334f36de622ecbd3a,NaN,NaN,NaN,NaN,650.0,17.0,14.0,12.0
128,d8dee61c2034d6d075997acef1870e9b,NaN,NaN,NaN,NaN,300.0,16.0,7.0,20.0
145,56139431d72cd51f19eb9f7dae4d1617,NaN,NaN,NaN,NaN,200.0,20.0,20.0,20.0
154,46b48281eb6d663ced748f324108c733,NaN,NaN,NaN,NaN,18500.0,41.0,30.0,41.0
197,5fb61f482620cb672f5e586bb132eae9,NaN,NaN,NaN,NaN,300.0,35.0,7.0,12.0
...,...,...,...,...,...,...,...,...,...
32515,b0a0c5dd78e644373b199380612c350a,NaN,NaN,NaN,NaN,1800.0,30.0,20.0,70.0
32589,10dbe0fbaa2c505123c17fdc34a63c56,NaN,NaN,NaN,NaN,800.0,30.0,10.0,23.0
32616,bd2ada37b58ae94cc838b9c0569fecd8,NaN,NaN,NaN,NaN,200.0,21.0,8.0,16.0
32772,fa51e914046aab32764c41356b9d4ea4,NaN,NaN,NaN,NaN,1300.0,45.0,16.0,45.0
32852,c4ceee876c82b8328e9c293fa0e1989b,NaN,NaN,NaN,NaN,700.0,28.0,3.0,43.0

In [25]:
products_clean_3 = products.copy()
products_clean_3.product_category_name.isna().sum()

np.int64(610)

In [26]:
values = {"product_category_name" : 'unknown'}
products_clean_3 = products_clean_3.fillna(values)
products_clean_3.product_category_name.isna().sum()

np.int64(0)

In [27]:
products.product_category_name.isna().sum()

np.int64(610)

### 2.3 In the same copy, fill the missing product_weight_g values with the median weight. Why the median and not the mean?

In the output:

mean is the average.
50% is the median.
max is the heaviest product.

Compare mean with 50%. If the mean is much bigger than the median, and max is far above the 75% row, a few very heavy products are pulling the average up. In this dataset you should see the mean noticeably above the median.

A rule of thumb

When the values are spread fairly evenly, the mean and median are close, and either works.
When the data is skewed, with a few very large values (weights, prices, incomes), use the median for a “typical” value.

In [31]:
products_clean_3.product_weight_g.describe()

count    32951.000000
mean      2276.376802
std       4281.926387
min          0.000000
25%        300.000000
50%        700.000000
75%       1900.000000
max      40425.000000
Name: product_weight_g, dtype: float64

In [28]:
products_clean_3.product_weight_g.isna().sum()

np.int64(2)

In [30]:
products_clean_3['product_weight_g'] = products_clean_3['product_weight_g'].fillna(products_clean_3.product_weight_g.median())
products_clean_3.product_weight_g.isna().sum()

np.int64(0)

### 2.4 Create orders_delivered: the rows of orders that have a non-null order_delivered_customer_date. How many rows were removed compared with orders?

Without subset, dropna would remove a row if any column is null.

In [46]:
orders_delivered = orders.dropna(subset=['order_delivered_customer_date'])
orders_delivered.shape

(96476, 8)

In [43]:
orders.shape

(99441, 8)

## Task 3 - Convert dtypes with astype, to_numeric and to_datetime

### 3.1 Print the dtypes of orders. Which columns hold dates but are stored as text?

In [47]:
orders.dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

### 3.2 Convert the five timestamp columns of orders to datetime in a loop. Check that the dtypes changed and the null counts did not.

In [51]:
orders.infer_objects().dtypes

order_id                         str
customer_id                      str
order_status                     str
order_purchase_timestamp         str
order_approved_at                str
order_delivered_carrier_date     str
order_delivered_customer_date    str
order_estimated_delivery_date    str
dtype: object

In [48]:
orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

In [49]:
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [54]:
cols = ['order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date']
for c in cols:
    orders[c] = pd.to_datetime(orders[c])

orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [55]:
orders.isna().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
order_estimated_delivery_date       0
dtype: int64

### 3.3 Make s = pd.Series(['10', '25', 'N/A', '7.5', 'abc']) and convert it to numbers with to_numeric(errors='coerce'). How many values became NaN? Why can errors='coerce' hide problems in real data?

In [58]:
s = pd.Series(['10','25','N/A','7.5','abc'])
pd.to_numeric(s,errors='coerce')

0    10.0
1    25.0
2     NaN
3     7.5
4     NaN
dtype: float64

### 3.4 Check the minimum and maximum of payment_installments in payments. Convert it to int8 if the values fit, and compare memory_usage() before and after.

In [59]:
payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [65]:
payments.dtypes

order_id                    str
payment_sequential        int64
payment_type                str
payment_installments      int64
payment_value           float64
dtype: object

In [60]:
payments.payment_installments.min()

np.int64(0)

In [61]:
payments.payment_installments.max()

np.int64(24)

In [72]:
#Memory usage before
payments['payment_installments'].memory_usage(deep=True)

104018

int8 holds -128 to 127. So, if min and max were out of the range, then the column would not be able to hold the values being int8 dtype.

In [67]:
payments['payment_installments'] = payments['payment_installments'].astype("int8")

In [68]:
payments.dtypes

order_id                    str
payment_sequential        int64
payment_type                str
payment_installments       int8
payment_value           float64
dtype: object

In [69]:
payments.payment_installments.min()

np.int8(0)

In [70]:
payments.payment_installments.max()

np.int8(24)

In [71]:
#Memory usage after
payments['payment_installments'].memory_usage(deep=True)

104018

## Task 4 - Find and drop duplicates with duplicated and drop_duplicates

### 4.1 For each of the 9 tables, count fully duplicated rows and print a name and count for each. Which table stands out?

In [78]:
orders.duplicated(subset='order_status', keep=False)

for name, df in tables.items():
    print(name, df.duplicated().sum())

olist_customers_dataset 0
olist_geolocation_dataset 261831
olist_orders_dataset 0
olist_order_items_dataset 0
olist_order_payments_dataset 0
olist_order_reviews_dataset 0
olist_products_dataset 0
olist_sellers_dataset 0
product_category_name_translation 0

### 4.2 In reviews, is review_id unique? Show 6 rows whose review_id appears more than once, sorted by review_id.

In [81]:
reviews.duplicated(subset='review_id').sum()

np.int64(814)

In [86]:
reviews[reviews.duplicated(subset='review_id')].sort_values(by='review_id').head(6)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
46678,00130cbe1f9d422698c812ed8ded1919,dfcdfc43867d1c1381bfaf62d6b9c195,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:23
90677,0115633a9c298b6a98bcbe4eee75345f,78a4201f58af3463bdab842eea4bc801,5,NaN,NaN,2017-09-21 00:00:00,2017-09-26 03:27:47
92876,0174caf0ee5964646040cd94e15ac95e,f93a732712407c02dce5dd5088d0f47b,1,NaN,Produto entregue dentro de embalagem do fornec...,2018-03-07 00:00:00,2018-03-08 03:00:53
99167,017808d29fd1f942d97e50184dfb4c13,b1461c8882153b5fe68307c46a506e39,5,NaN,NaN,2018-03-02 00:00:00,2018-03-05 01:43:30
96080,0254bd905dc677a6078990aad3331a36,331b367bdd766f3d1cf518777317b5d9,1,NaN,O pedido consta de 2 produtos e até agora rece...,2017-09-09 00:00:00,2017-09-13 09:52:44
94851,0288d42bef3dfe36930740c9588a570f,f889a5a0b44adc29c5465b99395ac3c1,3,NaN,NaN,2017-07-29 00:00:00,2017-07-31 17:11:04

In [87]:
#keep=False marks every copy, not just the later ones.
reviews[reviews.duplicated(subset='review_id',keep=False)].sort_values(by='review_id').head(6)

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
29841,00130cbe1f9d422698c812ed8ded1919,04a28263e085d399c97ae49e0b477efa,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:23
46678,00130cbe1f9d422698c812ed8ded1919,dfcdfc43867d1c1381bfaf62d6b9c195,1,NaN,"O cartucho ""original HP"" 60XL não é reconhecid...",2018-03-07 00:00:00,2018-03-20 18:08:23
63193,0115633a9c298b6a98bcbe4eee75345f,0c9850b2c179c1ef60d2855e2751d1fa,5,NaN,NaN,2017-09-21 00:00:00,2017-09-26 03:27:47
90677,0115633a9c298b6a98bcbe4eee75345f,78a4201f58af3463bdab842eea4bc801,5,NaN,NaN,2017-09-21 00:00:00,2017-09-26 03:27:47
57280,0174caf0ee5964646040cd94e15ac95e,74db91e33b4e1fd865356c89a61abf1f,1,NaN,Produto entregue dentro de embalagem do fornec...,2018-03-07 00:00:00,2018-03-08 03:00:53
92876,0174caf0ee5964646040cd94e15ac95e,f93a732712407c02dce5dd5088d0f47b,1,NaN,Produto entregue dentro de embalagem do fornec...,2018-03-07 00:00:00,2018-03-08 03:00:53

### 4.3 Reduce geolocation to one row per geolocation_zip_code_prefix using drop_duplicates with subset and keep='first'. How many rows remain? Why might keeping only the first row lose information?

Many rows share a zip prefix but have slightly different latitude and longitude. An average per zip prefix would be fairer than picking one.

In [90]:
geolocation_reduced = geolocation.drop_duplicates(subset='geolocation_zip_code_prefix',keep='first')
geolocation_reduced.shape

(19015, 5)

In [91]:
geolocation.shape

(1000163, 5)

### 4.4 Check whether order_id is unique in orders and in payments using is_unique. In one sentence, what does the difference mean for joining these two tables later?

In [93]:
orders.order_id.is_unique

True

In [94]:
payments.order_id.is_unique

False

In [97]:
payments[payments.duplicated(subset='order_id',keep=False)].sort_values('order_id')

,order_id,payment_sequential,payment_type,payment_installments,payment_value
80856,0016dfedd97fc2950e388d2971d718c7,2,voucher,1,17.92
89575,0016dfedd97fc2950e388d2971d718c7,1,credit_card,5,52.63
20036,002f19a65a2ddd70a090297872e6d64e,1,voucher,1,44.11
98894,002f19a65a2ddd70a090297872e6d64e,2,voucher,1,33.18
10244,0071ee2429bc1efdc43aa3e073a5290e,1,voucher,1,100.00
...,...,...,...,...,...
55988,ffa1dd97810de91a03abd7bd76d2fed1,1,credit_card,1,36.58
3009,ffa39020fe7c8a3e907320e1bec4b985,2,voucher,1,64.01
32912,ffa39020fe7c8a3e907320e1bec4b985,1,credit_card,1,7.13
28537,ffc730a0615d28ec19f9cad02cb41442,2,credit_card,1,12.63
75188,ffc730a0615d28ec19f9cad02cb41442,1,credit_card,1,14.76

## Exercise - In orders, parse all timestamp columns. Count how many delivered orders have a null delivery date, and decide what that means.

In [98]:
#In orders, parse all timestamp columns.
cols = ['order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date']
for c in cols:
    orders[c] = pd.to_datetime(orders[c])

orders.dtypes

order_id                                    str
customer_id                                 str
order_status                                str
order_purchase_timestamp         datetime64[us]
order_approved_at                datetime64[us]
order_delivered_carrier_date     datetime64[us]
order_delivered_customer_date    datetime64[us]
order_estimated_delivery_date    datetime64[us]
dtype: object

In [105]:
#Count how many delivered orders have a null delivery date

((orders.order_status == 'delivered') & (orders.order_delivered_customer_date.isnull())).sum()

np.int64(8)

In [106]:
orders[(orders.order_status == 'delivered') & (orders.order_delivered_customer_date.isnull())]

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
3002,2d1e2d5bf4dc7227b3bfebb81328c15f,ec05a6d8558c6455f0cbbd8a420ad34f,delivered,2017-11-28 17:44:07,2017-11-28 17:56:40,2017-11-30 18:12:23,NaT,2017-12-18
20618,f5dd62b788049ad9fc0526e3ad11a097,5e89028e024b381dc84a13a3570decb4,delivered,2018-06-20 06:58:43,2018-06-20 07:19:05,2018-06-25 08:05:00,NaT,2018-07-16
43834,2ebdfc4f15f23b91474edf87475f108e,29f0540231702fda0cfdee0a310f11aa,delivered,2018-07-01 17:05:11,2018-07-01 17:15:12,2018-07-03 13:57:00,NaT,2018-07-30
79263,e69f75a717d64fc5ecdfae42b2e8e086,cfda40ca8dd0a5d486a9635b611b398a,delivered,2018-07-01 22:05:55,2018-07-01 22:15:14,2018-07-03 13:57:00,NaT,2018-07-30
82868,0d3268bad9b086af767785e3f0fc0133,4f1d63d35fb7c8999853b2699f5c7649,delivered,2018-07-01 21:14:02,2018-07-01 21:29:54,2018-07-03 09:28:00,NaT,2018-07-24
92643,2d858f451373b04fb5c984a1cc2defaf,e08caf668d499a6d643dafd7c5cc498a,delivered,2017-05-25 23:22:43,2017-05-25 23:30:16,NaT,NaT,2017-06-23
97647,ab7c89dc1bf4a1ead9d6ec1ec8968a84,dd1b84a7286eb4524d52af4256c0ba24,delivered,2018-06-08 12:09:39,2018-06-08 12:36:39,2018-06-12 14:10:00,NaT,2018-06-26
98038,20edc82cf5400ce95e1afacc25798b31,28c37425f1127d887d7337f284080a0f,delivered,2018-06-27 16:09:12,2018-06-27 16:29:30,2018-07-03 19:26:00,NaT,2018-07-19